import { supabase } from './supabase';

function requireSupabase() { if (!supabase) throw new Error('Supabase no está configurado.'); return supabase; }
async function session() { const db=requireSupabase(); const {data,error}=await db.auth.getSession(); if(error) throw error; if(!data.session) throw new Error('Debes iniciar sesión.'); return data.session; }
async function staff(){ const db=requireSupabase(); const s=await session(); const {data,error}=await db.from('profiles').select('role,full_name,email,distrito_id').eq('id',s.user.id).maybeSingle(); if(error) throw error; if(!data||!['admin','coordinador','master_admin','evaluator','evaluador'].includes(data.role)) throw new Error('Tu cuenta no tiene permisos de gestión.'); return {db,session:s,profile:data}; }
function modelId(){ return localStorage.getItem('r17:modelId')||null; }

export async function getCurrentStaff(){ if(!supabase) return {session:null,role:null}; const s=await supabase.auth.getSession(); if(!s.data.session) return {session:null,role:null}; const p=await supabase.from('profiles').select('role,full_name,email,distrito_id').eq('id',s.data.session.user.id).maybeSingle(); return {session:s.data.session,role:p.data?.role||null,profile:p.data||null}; }
export async function listDistricts(){ const db=requireSupabase(); const {data,error}=await db.from('distritos').select('id,nombre,regional').order('id'); if(error) throw error; return data||[]; }
export async function listPeriods(){ const db=requireSupabase(); const {data,error}=await db.from('scoreboard_periods').select('*').order('created_at',{ascending:false}); if(error) throw error; return data||[]; }
export async function createPeriod(payload){ const {db,session:s}=await staff(); const {data,error}=await db.from('scoreboard_periods').insert({...payload,created_by:s.user.id}).select('*').single(); if(error) throw error; return data; }
export async function updatePeriod(id,payload){ const {db}=await staff(); const {data,error}=await db.from('scoreboard_periods').update({...payload,updated_at:new Date().toISOString()}).eq('id',id).select('*').single(); if(error) throw error; return data; }
export async function deletePeriod(id){ const {db}=await staff(); const {error}=await db.from('scoreboard_periods').delete().eq('id',id); if(error) throw error; }
export async function listModels(){ const db=requireSupabase(); const {data,error}=await db.from('scoreboard_models').select('id,nombre,descripcion,fecha,estado,distrito_id,periodo_id,distritos(id,nombre),scoreboard_periods(id,nombre,estado)').order('created_at',{ascending:false}); if(error) throw error; return (data||[]).map(m=>({...m,distrito:m.distritos?.nombre||m.distrito_id,periodo:m.scoreboard_periods?.nombre||''})); }
export async function createModel(payload){ const {db,session:s}=await staff(); const {data,error}=await db.from('scoreboard_models').insert({...payload,created_by:s.user.id}).select('id,nombre,descripcion,fecha,estado,distrito_id,periodo_id').single(); if(error) throw error; return data; }
export async function updateModel(id,payload){ const {db}=await staff(); const {data,error}=await db.from('scoreboard_models').update({...payload,updated_at:new Date().toISOString()}).eq('id',id).select('id,nombre,descripcion,fecha,estado,distrito_id,periodo_id').single(); if(error) throw error; return data; }
export async function deleteModel(id){ const {db}=await staff(); const {error}=await db.from('scoreboard_models').delete().eq('id',id); if(error) throw error; }
export async function listCommissions(model_id=modelId()){ const db=requireSupabase(); if(!model_id) return []; const {data,error}=await db.from('scoreboard_commissions').select('id,nombre,descripcion,activo,orden').eq('model_id',model_id).eq('activo',true).order('orden').order('nombre'); if(error) throw error; return data||[]; }
export async function createCommission({model_id=modelId(),nombre,descripcion='',orden=0}){ const {db}=await staff(); if(!model_id) throw new Error('Selecciona un modelo activo.'); const {data,error}=await db.from('scoreboard_commissions').insert({model_id,nombre:nombre.trim(),descripcion,orden}).select('*').single(); if(error) throw error; return data; }
export async function updateCommission(id,payload){ const {db}=await staff(); const {data,error}=await db.from('scoreboard_commissions').update({...payload,updated_at:new Date().toISOString()}).eq('id',id).select('*').single(); if(error) throw error; return data; }
export async function deleteCommission(id){ const {db}=await staff(); const {error}=await db.from('scoreboard_commissions').delete().eq('id',id); if(error) throw error; }
export async function listDelegates(model_id=modelId()){ const db=requireSupabase(); if(!model_id) return []; const {data,error}=await db.from('scoreboard_delegates').select('id,nombre,pais,nuid,modelo_comite,checked_in,activo,created_at').eq('model_id',model_id).eq('activo',true).order('nombre'); if(error) throw error; return (data||[]).map(d=>({id:d.id,name:d.nombre,country:d.pais,nuid:d.nuid||'',model:d.modelo_comite||'',checked_in:d.checked_in,created_at:d.created_at})); }
export async function createDelegate({name,country,model,nuid}){ const {db,session:s}=await staff(); const mid=modelId(); if(!mid) throw new Error('Selecciona un modelo activo.'); if(!name?.trim()||!country?.trim()) throw new Error('El nombre y el país son obligatorios.'); const {data,error}=await db.from('scoreboard_delegates').insert({model_id:mid,nombre:name.trim(),pais:country.trim(),modelo_comite:model?.trim()||null,nuid:nuid?.trim()||null,created_by:s.user.id}).select('*').single(); if(error) throw error; return {id:data.id,name:data.nombre,country:data.pais,model:data.modelo_comite||'',nuid:data.nuid||'',checked_in:data.checked_in}; }
export async function updateDelegate(delegateId,{name,country,model,nuid}){ const {db}=await staff(); const {data,error}=await db.from('scoreboard_delegates').update({nombre:name.trim(),pais:country.trim(),modelo_comite:model?.trim()||null,nuid:nuid?.trim()||null,updated_at:new Date().toISOString()}).eq('id',delegateId).select('*').single(); if(error) throw error; return {id:data.id,name:data.nombre,country:data.pais,model:data.modelo_comite||'',nuid:data.nuid||'',checked_in:data.checked_in}; }
export async function deleteDelegate(delegateId){ const {db}=await staff(); const {error}=await db.from('scoreboard_delegates').delete().eq('id',delegateId); if(error) throw error; }
export async function setDelegateAttendance(delegateId,checkedIn){ const {db}=await staff(); const {data,error}=await db.from('scoreboard_delegates').update({checked_in:checkedIn,updated_at:new Date().toISOString()}).eq('id',delegateId).select('id,checked_in').single(); if(error) throw error; return data; }
export async function saveEvaluation({delegateId,commissionId,evaluatorId,scores,total,comments}){ const {db,session:s}=await staff(); if(evaluatorId!==s.user.id) throw new Error('El evaluador debe coincidir con la cuenta autenticada.'); const mid=modelId(); if(!mid) throw new Error('Selecciona un modelo activo.'); const {data,error}=await db.from('scoreboard_evaluations').insert({model_id:mid,delegate_id:delegateId,commission_id:commissionId||null,evaluator_id:evaluatorId,scores,total:Number(total||0),comments:comments||null}).select('id').single(); if(error) throw error; return data; }
export async function listEvaluations(model_id=modelId()){ const db=requireSupabase(); if(!model_id) return []; let q=db.from('scoreboard_evaluations').select('id,delegate_id,commission_id,evaluator_id,scores,total,comments,created_at,scoreboard_delegates(nombre,pais,modelo_comite),scoreboard_commissions(nombre)').order('created_at',{ascending:false}); if(model_id) q=q.eq('model_id',model_id); const {data,error}=await q; if(error) throw error; return (data||[]).map(row=>({id:row.id,delegateId:row.delegate_id,delegateName:row.scoreboard_delegates?.nombre||'Delegado',country:row.scoreboard_delegates?.pais||'',model:row.scoreboard_delegates?.modelo_comite||'',commission:row.scoreboard_commissions?.nombre||'',evaluatorId:row.evaluator_id,scores:row.scores||{},total:Number(row.total),comments:row.comments||'',savedAt:row.created_at})); }
export async function listUsers(){ const db=requireSupabase(); const {data,error}=await db.from('profiles').select('id,full_name,email,role,distrito_id').order('full_name'); if(error) throw error; return data||[]; }
export async function updateUserRole(id,payload){ const {db}=await staff(); const {data,error}=await db.from('profiles').update(payload).eq('id',id).select('id,full_name,email,role,distrito_id').single(); if(error) throw error; return data; }
